### ISSUE TITLE
Hello. It works but show this log endless.

### ISSUE THREAD

**Issue by acttoz** [natmlx/NatML#24] opened 2022-08-30 02:19 UTC
2022-08-17 16:47:47.774 31226 31374 Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
2022-08-17 16:47:47.774 31226 31374 Error NatML CameraDevice 1 failed to read preview image
2022-08-17 16:47:47.774 31226 31374 Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
2022-08-17 16:47:47.774 31226 31374 Error NatML CameraDevice 1 failed to read preview image
2022-08-17 16:47:47.774 31226 31374 Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
2022-08-17 16:47:47.774 31226 31374 Error NatML CameraDevice 1 failed to read preview image
2022-08-17 16:47:47.774 31226 31374 Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
2022-08-17 16:47:47.774 31226 31374 Error NatML CameraDevice 1 failed to read preview image
2022-08-17 16:47:47.774 31226 31374 Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
2022-08-17 16:47:47.774 31226 31374 Error NatML CameraDevice 1 failed to read preview image

**Comment by olokobayusuf** [comment] 2022-08-30 18:48
Closing as duplicate of #25

**Closed by olokobayusuf** 2022-08-30 18:48 UTC
Labels: duplicate
