### ISSUE TITLE
Async `MLEdgeModel.Create` is still blocking the main thread on Android

### ISSUE THREAD

**Issue by joseph-o3h** [natmlx/natml#49] opened 2023-03-15 03:41 UTC
<img width="1093" alt="Screen Shot 2023-03-14 at 20 04 27" src="https://user-images.githubusercontent.com/91497173/225200109-b12aa499-23c8-41df-b96b-2e7d51140cc4.png">

These are the models being loaded (both are embedded):
* `@natml/blazepose-detector`
* `@natml/blazepose-landmark`

This cannot be solved by calling `MLEdgeModel.Create` on a non-main thread as it makes a call to `PlayerPrefs.GetString` which is a main thread only API.

Happens on latest NatML (1.1.3)

**Comment by olokobayusuf** [comment] 2023-03-20 19:29
@joseph-o3h found the cause to be some very weird C++ quirk. Fix coming later today or tomorrow morning.

**Comment by olokobayusuf** [comment] 2023-03-23 21:49
@joseph-o3h fixed in [NatML 1.1.4](https://github.com/natmlx/natml/releases/tag/1.1.4). Thank you so much for catching this!

**Comment by olokobayusuf** [comment] 2023-03-23 21:49
Oh, and `MLEdgeModel.Create` can now be called from any arbitrary thread. That was also an excellent catch ;)

**Closed by olokobayusuf** 2023-03-23 21:49 UTC
Labels: android, bug, critical
