### ISSUE TITLE
Build on Android doesn't work, but in the Editor is ok

### ISSUE THREAD

**Issue by TomaszWozniakMosina** [natmlx/NatML#18] opened 2022-07-20 12:49 UTC
Hi,
When Fetching data starts on Android, I get NullReferenceException: Object reference not set to an instance of an object

But in Editor it works ok.

Thanks in advance for help

**Comment by olokobayusuf** [comment] 2022-07-21 16:16
Duplicate off #19

**Closed by olokobayusuf** 2022-07-21 16:16 UTC
Labels: duplicate
