### ISSUE TITLE
Hello. It works but show this message endless loop line.

### ISSUE THREAD

**Issue by acttoz** [natmlx/NatML#25] opened 2022-08-30 02:20 UTC
What can I do to fix it?

Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
Warn NdkImageReader Unable to acquire a lockedBuffer, very likely client tries to lock more than maxImages buffers
...

**Comment by olokobayusuf** [comment] 2022-08-30 18:48
Duplicate of #22

**Closed by olokobayusuf** 2022-08-30 18:48 UTC
Labels: duplicate
